version: "3"

services:
  app:
    build: .
    links:
      - redis
    environment:
      - REDIS_URL: redis:6379
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data
